name: snap-helpers-testapp
version: git
summary: Snap for a test application using snap-helpers
description: |
  Snap for a test application using snap-helpers.
grade: stable
confinement: strict
base: core18

apps:
  python:
    command: usr/bin/python3
    plugs:
      - home
      - network
      - network-bind
  ipython:
    command: bin/ipython3
    plugs:
      - home
      - network
      - network-bind
  service1:
    command: bin/service1
    daemon: simple
  service2:
    command: bin/service2
    daemon: simple

hooks:
  configure:
    plugs: []
  install:
    plugs: []

parts:
  snap-helpers-testapp:
    plugin: python
    python-version: python3
    source: .
    requirements:
      - requirements.txt
    python-packages:
      - ipython
    build-packages:
      - python3-dev
    stage-packages:
      - libpython3.6
    override-build: |
      set -e

      snapcraftctl build
      snap-helpers write-hooks
