name: snap-helpers-testapp
version: git
summary: Snap for a test application using snap-helpers
description: |
  Snap for a test application using snap-helpers.
grade: stable
confinement: strict
base: core22

plugs:
  snap-helpers-lib:
    interface: content
    content: snap-helpers-lib
    target: $SNAP/lib/python3.10/site-packages/snaphelpers
    default-provider: snap-helpers

apps:
  python:
    command: bin/python3
    plugs:
      - home
      - network
      - network-bind
  ipython:
    command: bin/ipython3
    plugs:
      - home
      - network
      - network-bind
  service1:
    command: bin/service1
    daemon: simple
  service2:
    command: bin/service2
    daemon: simple

parts:
  snap-helpers-testapp:
    plugin: python
    source: .
    source-type: git
    python-packages:
      - ipython
    after:
      - snap-helpers
    override-build: |
      craftctl default
      snap-helpers write-hooks
