name: snap-helpers
version: git
summary: Test snap for the snap-helpers Python library.
description: |
  Test snap for the snap-helpers Python library.

  It provides python and ipython shells to interact and test the `snaphelpers`
  library.

  See the https://github.com/albertodonato/snap-helpers for more details.
license: LGPL-3.0
website: https://github.com/albertodonato/snap-helpers
source-code: https://github.com/albertodonato/snap-helpers
contact: https://github.com/albertodonato/snap-helpers/issues
issues: https://github.com/albertodonato/snap-helpers/issues

base: core22
grade: stable
confinement: strict

slots:
  snap-helpers-lib:
    interface: content
    content: snap-helpers-lib
    read:
      - $SNAP/lib/python3.10/site-packages/snaphelpers

apps:
  snap-helpers:
    command: bin/snap-helpers-shell
    plugs:
      - home
      - network
      - network-bind
  python:
    command: bin/python3
    plugs:
      - home
      - network
      - network-bind

parts:
  snap-helpers:
    plugin: python
    source: .
    python-packages:
      - .
      - ipython

  local:
    plugin: dump
    source: snap/local
