name: snap-helpers
version: git
summary: Test snap for the snap-helpers Python library.
description: |
  Test snap for the snap-helpers Python library.

  It provides python and ipython shells to interact and test the `snaphelpers`
  library.

  See the https://github.com/albertodonato/snap-helpers for more details.

license: LGPL-3.0
grade: stable
confinement: strict
base: core20

slots:
  snap-helpers-lib:
    interface: content
    content: snap-helpers-lib
    read:
      - $SNAP/lib/python3.8/site-packages/snaphelpers

apps:
  snap-helpers:
    command: bin/snap-helpers-shell
    plugs:
      - home
      - network
      - network-bind
  python:
    command: usr/bin/python3
    plugs:
      - home
      - network
      - network-bind

parts:
  snap-helpers:
    plugin: python
    python-version: python3
    source: .
    python-packages:
      - ipython
    build-packages:
      - python3-dev
    stage-packages:
      - libpython3.8

  local:
    plugin: dump
    source: snap/local
