name: snap-helpers
version: git
summary: Test snap for the snap-helpers Python library.
description: |
  Test snap for the [snap-helpers](https://pypi.org/project/snap-helpers/)
  library.

  It provides python and ipython shells to interact and test the `snaphelpers`
  library.

  See the [project repository](https://github.com/albertodonato/snap-helpers)
  for more details.

grade: stable
confinement: strict
base: core18

apps:
  snap-helpers:
    command: bin/snap-helpers-shell
    plugs:
      - home
      - network
      - network-bind
  python:
    command: usr/bin/python3
    plugs:
      - home
      - network
      - network-bind
  ipython:
    command: bin/ipython3
    plugs:
      - home
      - network
      - network-bind

parts:
  snap-helpers:
    plugin: python
    python-version: python3
    source: .
    python-packages:
      - ipython
    build-packages:
      - python3-dev
    stage-packages:
      - libpython3.6

  local:
    plugin: dump
    source: snap/local
