name: snap-helpers
version: git
summary: Test snap for snap-helpers
description: |
  Test snap for snap-helpers.

  It provides python and ipython shells to test the `snaphelpers` library.

grade: stable
confinement: strict
base: core18

apps:
  snap-helpers:
    command: bin/snap-helpers-shell
    plugs:
      - home
      - network
      - network-bind
  python:
    command: usr/bin/python3
    plugs:
      - home
      - network
      - network-bind
  ipython:
    command: bin/ipython3
    plugs:
      - home
      - network
      - network-bind

parts:
  snap-helpers:
    plugin: python
    python-version: python3
    source: .
    python-packages:
      - ipython
    build-packages:
      - python3-dev
    stage-packages:
      - libpython3.6

  local:
    plugin: dump
    source: snap/local
