name: testapp
version: git
summary: Snap for a test application using snap-helpers
description: |
  Snap for a test application using snap-helpers.
grade: stable
confinement: strict
base: core18

apps:
  python:
    command: usr/bin/python3
    plugs:
      - home
      - network
      - network-bind
  ipython:
    command: bin/ipython3
    plugs:
      - home
      - network
      - network-bind

hooks:
  configure:
    plugs: []
  install:
    plugs: []

parts:
  snap-helpers:
    plugin: python
    python-version: python3
    source: ..
    build-packages:
      - python3-dev
    stage-packages:
      - libpython3.6

  testapp:
    plugin: python
    python-version: python3
    source: .
    python-packages:
      - ipython
    build-packages:
      - python3-dev
    stage-packages:
      - libpython3.6
    after:
      - snap-helpers
    override-build: |
      set -e

      snapcraftctl build
      snap-helpers write-hooks
