name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    strategy:
      matrix:
        include:
          - python-version: "3.8"
            platform: ubuntu-20.04
          - python-version: "3.10"
            platform: ubuntu-22.04
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Repository checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install --upgrade pip tox

      - name: Lint
        run: |
          tox run -e lint

  check:
    strategy:
      matrix:
        include:
          - python-version: "3.8"
            platform: ubuntu-20.04
          - python-version: "3.10"
            platform: ubuntu-22.04
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Repository checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install --upgrade pip tox

      - name: Check
        run: |
          tox run -e check

  test:
    strategy:
      matrix:
        include:
          - python-version: "3.8"
            platform: ubuntu-20.04
          - python-version: "3.10"
            platform: ubuntu-22.04
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Repository checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install --upgrade pip tox

      - name: Test
        run: |
          tox run -e coverage
