name: Integration tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  integration-tests:
    strategy:
      matrix:
        base:
          - core20
          - core22
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Repository checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install --upgrade pip tox

      - name: Prepare build
        run: |
          make -C test-snap setup BASE=${{ matrix.base }}

      - name: Build snap
        id: build-snap
        uses: snapcore/action-build@v1
        with:
          path: test-snap

      - name: Install snap
        run: |
          sudo snap install --dangerous ${{ steps.build-snap.outputs.snap }}

      - name: Run tests
        run: |
          snap_common=/var/snap/snap-helpers-testapp/common
          sudo cp integration_tests.py $snap_common
          env -C $snap_common -- sudo snap-helpers-testapp.pytest -vs integration_tests.py
